version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: minimart
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: minimart_dev
    ports:
      - \"5432:5432\"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
