services:

  # The Go application service
  app:
    build: . # Build the image from the Dockerfile in the currect directory
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./config.yaml:/app/config.yaml # Mount the config file into ther container
    depends_on:
      - redis # Ensure redis starts before the app
    environment:
      # Environment variables for the app
      - PORT=3000
      - DATABASE_URL=postgres://minimart:secret@db:5432/minimart_dev
      - REDIS_URL=redis:6379
      - JWT_SECRET=a-very-secret-key-that-is-long-and-secure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: minimart
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: minimart_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
