services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: minimart
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: minimart_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
