// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"bg-gray-800 text-white mt-auto\"><div class=\"max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8\"><div class=\"grid grid-cols-1 md:grid-cols-4 gap-8\"><!-- Brand --><div class=\"col-span-1 md:col-span-2\"><h3 class=\"text-lg font-bold mb-2\">⚡ Minimart</h3><p class=\"text-gray-400 mb-4\">The first Bitcoin-native food ordering platform.  Pay in sats, order instantly, eat locally.</p><div class=\"flex items-center space-x-2\"><div class=\"w-4 h-4 bg-orange-500 rounded-full\"></div><span class=\"text-sm text-gray-400\">Lightning Network Ready</span></div></div><!-- Quick Links --><div><h4 class=\"font-semibold mb-4\">Quick Links</h4><ul class=\"space-y-2\"><li><a href=\"/menu\" class=\"text-gray-400 hover:text-white transition-colors\">Browse Menu</a></li><li><a href=\"/about\" class=\"text-gray-400 hover:text-white transition-colors\">About Us</a></li><li><a href=\"/help\" class=\"text-gray-400 hover:text-white transition-colors\">Help Center</a></li><li><a href=\"/merchants/apply\" class=\"text-gray-400 hover:text-white transition-colors\">Become a Merchant</a></li></ul></div><!-- Bitcoin Info --><div><h4 class=\"font-semibold mb-4\">Bitcoin Payment</h4><ul class=\"space-y-2\"><li class=\"text-gray-400 text-sm\">✓ Lightning Network</li><li class=\"text-gray-400 text-sm\">✓ On-chain Bitcoin</li><li class=\"text-gray-400 text-sm\">✓ Low fees</li><li class=\"text-gray-400 text-sm\">✓ Instant confirmation</li></ul></div></div><div class=\"mt-8 pt-8 border-t border-gray-700 flex flex-col md:flex-row justify-between items-center\"><p class=\"text-gray-400 text-sm\">© 2025 Minimart. All rights reserved. Built with ⚡ and 🧡.</p><div class=\"mt-4 md:mt-0 text-gray-400 text-sm\">Powered by  <a href=\"https://bitcoin.org\" target=\"_blank\" class=\"text-orange-400 hover:text-orange-300\">Bitcoin</a></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
