// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "minimart/types"

func Nav(user *types.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-white shadow-sm border-b border-gray-200\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"flex justify-between items-center h-16\"><!-- Logo --><div class=\"flex items-center\"><a href=\"/\" class=\"text-xl font-bold text-orange-600\">⚡ Minimart</a> <span class=\"ml-2 text-xs bg-orange-100 text-orange-800 px-2 py-1 rounded-full\">Bitcoin Native</span></div><!-- Navigation Links --><div class=\"hidden md:flex items-center space-x-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if user != nil {
			if user.Role == "customer" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/menu\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Menu</a> <a href=\"/orders\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">My Orders</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if user.Role == "merchant" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/merchant/dashboard\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Dashboard</a> <a href=\"/merchant/menu\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Manage Menu</a> <a href=\"/merchant/orders\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Orders</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"/menu\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Menu</a> <a href=\"/about\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">About</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- User Actions --><div class=\"flex items-center space-x-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if user != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- User Menu --> <div class=\"relative\"><button data-on-click=\"$userMenuOpen = !$userMenuOpen\" class=\"flex items-center space-x-2 text-sm text-gray-700 hover:text-orange-600 transition-colors\"><div class=\"w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center\"><span class=\"text-orange-600 font-medium\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(user.Username[:1])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/shared/templates/components/nav.templ`, Line: 46, Col: 97}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span></div><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(user.Username)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/shared/templates/components/nav.templ`, Line: 48, Col: 53}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span> <svg class=\"w-4 h-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 9l-7 7-7-7\"></path></svg></button><!-- Dropdown menu --><div data-show=\"$userMenuOpen\" data-on-click-outside=\"$userMenuOpen = false\" class=\"absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 ring-1 ring-black ring-opacity-5\"><a href=\"/profile\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50\">Profile</a> <a href=\"/settings\" class=\"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50\">Settings</a><hr class=\"my-1\"><button data-on-click=\"$$post('/auth/logout')\" class=\"w-full text-left block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50\">Sign out</button></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<!-- Auth buttons --> <a href=\"/auth/login\" class=\"text-gray-700 hover:text-orange-600 transition-colors\">Sign in</a> <a href=\"/auth/register\" class=\"bg-orange-600 hover:bg-orange-700 text-white px-4 py-2 rounded-md transition-colors\">Sign up</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div><!-- Mobile menu button --><div class=\"md:hidden\"><button data-on-click=\"$mobileMenuOpen = !$mobileMenuOpen\" class=\"text-gray-700 hover:text-orange-600\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button></div></div><!-- Mobile menu --><div data-show=\"$mobileMenuOpen\" class=\"md:hidden border-t border-gray-200\"><div class=\"px-2 pt-2 pb-3 space-y-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if user != nil {
			if user.Role == "customer" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<a href=\"/menu\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Menu</a> <a href=\"/orders\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">My Orders</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if user.Role == "merchant" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<a href=\"/merchant/dashboard\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Dashboard</a> <a href=\"/merchant/menu\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Manage Menu</a> <a href=\"/merchant/orders\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Orders</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " <hr class=\"my-2\"><a href=\"/profile\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Profile</a> <button data-on-click=\"$$post('/auth/logout')\" class=\"w-full text-left block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Sign out</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<a href=\"/menu\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Menu</a> <a href=\"/about\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">About</a><hr class=\"my-2\"><a href=\"/auth/login\" class=\"block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md\">Sign in</a> <a href=\"/auth/register\" class=\"block px-3 py-2 bg-orange-600 text-white hover:bg-orange-700 rounded-md\">Sign up</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div></div></div></nav><!-- Initialize mobile menu state --><script>\n        document.addEventListener('DOMContentLoaded', function() {\n            if (window.Datastar) {\n                Datastar.store.signals.mobileMenuOpen = false;\n                Datastar.store.signals.userMenuOpen = false;\n            }\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
